apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.global.stage | default "develop" }}-batch
  labels:
    app: batch
    stage: {{ .Values.global.stage | default "develop" }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    build: "{{ .Chart.AppVersion }}"
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: batch
        stage: {{ .Values.global.stage | default "develop" }}
    spec:
      initContainers:
        - name: validatedb
          image: craftypenguins/k8s-init-mysql:latest
          env:
            - name: DBUSER
              value: {{ .Values.mariadb.mariadbUser | default "develop" | quote }}
            - name: DBPASSWORD
              value: {{ .Values.mariadb.mariadbPassword | default "develop" | quote }}
            - name: DBHOST
              value: {{ .Values.mariadb.mariadbHostname | quote }}
            - name: DBNAME
              value: {{ .Values.mariadb.mariadbDatabase | quote }}
            - name: TIMEOUT
              value: "10s"
        {{- if .Values.istio.enabled }}
        - name: istio-init
          args:
          - -p
          - "15001"
          - -u
          - "1337"
          - -i
          - "10.0.0.0/8"
          image: docker.io/istio/proxy_init:0.7.1
          imagePullPolicy: IfNotPresent
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
        {{- end }}
      containers:
        - name: batch
          image: '{{ .Values.global.imagebase | default "yonadev" }}/batchservice:build-{{ .Chart.AppVersion }}'
          #imagePullPolicy: Always
          env:       
            - name: YONA_DB_USER_NAME
              value: {{ .Values.mariadb.mariadbUser | default "develop" | quote }}
            - name: YONA_DB_PASSWORD
              value: {{ .Values.mariadb.mariadbPassword | default "develop" | quote }}
            - name: YONA_DB_URL
            {{- if .Values.mariadb.url_override}}
              value: {{ .Values.mariadb.url_override | quote }}
            {{- else }}
              value: "jdbc:mariadb://{{ .Values.mariadb.mariadbHostname }}/{{ .Values.mariadb.mariadbDatabase }}"
            {{- end }}
          ports:
            - containerPort: 8080
            - containerPort: 9080
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app/config
          livenessProbe:
            httpGet:
              path: /health/
              port: 9080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
        {{- if .Values.istio.enabled }}
        - name: istio-proxy
          args:
            - proxy
            - sidecar
            - --configPath
            - /etc/istio/proxy
            - --binaryPath
            - /usr/local/bin/envoy
            - --serviceCluster
            - batch
            - --drainDuration
            - 45s
            - --parentShutdownDuration
            - 1m0s
            - --discoveryAddress
            - istio-pilot.istio-system:8080
            - --discoveryRefreshDelay
            - 1s
            - --zipkinAddress
            - zipkin.istio-system:9411
            - --connectTimeout
            - 10s
            - --statsdUdpAddress
            - istio-mixer.istio-system:9125
            - --proxyAdminPort
            - "15000"
            - --controlPlaneAuthPolicy
            - NONE
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: docker.io/istio/proxy:0.7.1
          imagePullPolicy: IfNotPresent
          resources: {}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
          volumeMounts:
            - mountPath: /etc/istio/proxy
              name: istio-envoy
            - mountPath: /etc/certs/
              name: istio-certs
              readOnly: true
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.AppVersion }}-{{ .Values.global.stage | default "develop" }}-springboot
        {{- if .Values.istio.enabled }}
        - name: istio-envoy
          emptyDir:
            medium: Memory
        - name: istio-certs
          secret:
            optional: true
            secretName: istio.default
        {{- end }}
