###########################################
# Configuration data container
###########################################
configuration:
  image: busybox
  volumes:
    - ./config:/opt/app/config:ro

###########################################
# Database
###########################################

hsqldb:
  image: yonadev/yonahsqldb:$yonatag
  restart: unless-stopped
  expose:
    - "9001"

###########################################
# Cache
###########################################

hazelcast:
  image: hazelcast/hazelcast
  restart: unless-stopped
  environment:
    - JAVA_OPTS="-Dhazelcast.config=./config/hazelcast.xml"
  expose:
    - "9002"
	
hazelcast-management-center:
  image: hazelcast/management-center
  environment:
    - HAZELCAST_IP={{hazelcast || container_private_ip}}
  ports:
    - 8090:8080
  links:
    - hazelcast
	
###########################################
# Services
###########################################

adminservice:
  image: yonadev/adminservice:$yonatag
  restart: unless-stopped
  links:
    - hsqldb:yonadbserver
  ports:
    - 8080:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

analysisservice:
  image: yonadev/analysisservice:$yonatag
  restart: unless-stopped
  links:
    - hsqldb:yonadbserver
  ports:
    - 8081:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

appservice:
  image: yonadev/appservice:$yonatag
  restart: unless-stopped
  links:
    - hsqldb:yonadbserver
  ports:
    - 80:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

batchservice:
  image: yonadev/batchservice:$yonatag
  restart: unless-stopped
  links:
    - hsqldb:yonadbserver
  ports:
    - 8083:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro
