###########################################
# Configuration data container
###########################################
configuration:
  image: busybox
  volumes:
    - ./config:/opt/app/config:ro

###########################################
# Database
###########################################

hsqldb:
  image: yonadev/yonahsqldb:0.0.8-SNAPSHOT
  expose:
    - "9001"

###########################################
# Services
###########################################

adminservice:
  image: yonadev/adminservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
  ports:
    - 8080:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

analysisservice:
  image: yonadev/analysisservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
  ports:
    - 8081:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

appservice:
  image: yonadev/appservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
  ports:
    - 80:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

batchservice:
  image: yonadev/batchservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
  ports:
    - 8083:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro
