language: java

jdk:
  - oraclejdk8

sudo: required

branches:
  only:
    - master

services:
  - docker

before_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || true'

script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew check build || ./gradlew check'
