###########################################
# Configuration data container
###########################################
configuration:
  image: busybox
  volumes:
    - ./config:/opt/app/config:ro
    - ./config:/config:ro

###########################################
# Logging: ELK stack copied from http://www.labouisse.com/how-to/2015/09/23/elk-docker-and-spring-boot/
###########################################

elasticsearch:
  image: elasticsearch
  volumes:
      - /usr/share/elasticsearch/data
  ports:
      - "9200:9200"

logstash:
  image: logstash
  environment:
      TZ: Europe/Paris
  expose:
    - "12201"
  ports:
      - "12201:12201"
      - "12201:12201/udp"
  volumes_from:
      - configuration:ro
  links:
      - elasticsearch:db
  command: logstash -f /config/gelf.conf

kibana:
  image: kibana
  links:
      - elasticsearch:elasticsearch
  ports:
      - "5601:5601"

###########################################
# Database
###########################################

hsqldb:
  image: yonadev/yonahsqldb:0.0.8-SNAPSHOT
  expose:
    - "9001"

###########################################
# Services
###########################################

adminservice:
  image: yonadev/adminservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
    - logstash
  ports:
    - 8080:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

analysisservice:
  image: yonadev/analysisservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
    - logstash
  ports:
    - 8081:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro

appservice:
  image: yonadev/appservice:0.0.8-SNAPSHOT
  links:
    - hsqldb:yonadbserver
    - logstash
  ports:
    - 80:8080
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"
  volumes_from:
        - configuration:ro
