version: '2'
networks:
  yonanet:
    external: true

services:
  hsqldb:
    image: yonadev/hsqldb:2.3.3
    container_name: hsqldb
    restart: unless-stopped
    logging:
        driver: "gelf"
        options:
          gelf-address: "udp://log:12201"
    networks:
      - yonanet
    expose:
      - "9001"
